const catchAsync = require('../error_handlers/catchAsync')
const User = require('../user/userModel');
const authUtils = require('./authUtils')
const AppError = require('../error_handlers/appError')
const apiKeyUtils = require('./apiKeyUtils')

exports.register = catchAsync( async(req,res,next)=>{
 try{
    if(req.body.password !== req.body.confirmPassword){
        next(new AppError('Password must be the same!',400))
    }
    // it should be generated by some algorithm
    const apiKey = apiKeyUtils.apiKeyGenerator(24)
    const secretKey = apiKeyUtils.apiKeyGenerator(12)
    const newUser = await User.create({
        phoneNumber:req.body.phoneNumber,
        password:req.body.password,
        confirmPassword:req.body.confirmPassword,
        apiKey:apiKey,
        secretKey:secretKey
    });
    const token = authUtils.signToken(newUser._id);
    res.status(201).json({
        status:"201_CREATED",
        data:{
            token,
            role:newUser.role,
            apiKey:newUser.apiKey
        }
    });
 }

 catch(err){
    next(new AppError(err,400))
 }
})



// Login controller.
exports.login = catchAsync(async(req,res,next )=>{
    try{
        if(!(req.body.password && req.body.phoneNumber)){
            next(new AppError('Both phone number{phoneNumber} and password{password} should be provided to login !',400));
        }    
         // after being sure we have both phone number and password for the user.
         const user = await User.findOne({
            phoneNumber:req.body.phoneNumber
         }).select('+password');
        
         if(user){
            const correct = await user.correctPassword(req.body.password,user.password);
            if(correct){
                const token  = authUtils.signToken(user._id);
                res.status(200).json({
                    status:'Successful',
                    data:{
                      token,
                      role:user.role  
                    }
                })
            }
            else{
                next(new AppError("User phoneNumber doesn't exits or the password is not correct!",400))
            }
         }
         else{
            next(new AppError("User phoneNumber doesn't exits or the password is not correct!",400))
         }
    }

    catch(err){
        next(new AppError(err,400))
    }
    });

    exports.changeSecretKey = catchAsync(async (req,res,next)=>{
        try{
            const pk = req.user.id
            const data = {
                secretKey : req.body.secretKey
            }
            const updatedUser = await User.findOneAndUpdate(pk,data,{
                new:true,
                runValidators:true,
            })   

            
res.status(201).json({
    status:"201_UPDATED",
    data:{
user: updatedUser
    }
})
        }
    catch(err){
        next(new AppError(err,400))
    }   
 })